<?php

return array(
	'How much should I be bidding?' => 'To win traffic, you need to bid high enough. This is the first rule of RTB! This amount varies from site to site, but we have data in the system (average CPM) that attempts to provide guidelines. These numbers are derived from data on our system, so they should not be taken as absolute, simply because we cannot account for the data on traffic we don’t win (i.e., data from other platforms).<p> Of course, you could always approach it casually and start with a low bid and steadily increase your bids until you start winning. Once you start to win traffic, you will know your eCPM, which is the true cost traffic. Once you have this number (eCPM), you will know what to bid based on first-hand data. To mitigate any unnecessary loss of ad spend during this test, you can set a low daily spend cap of $5 to$10.<p> No matter what your bid value is, you will only ever win traffic at $0.01 above what the next highest bidder was willing to pay. This will be evident in your eCPM column, as it will reflect what you are winning traffic for versus the default bid, which you should consider the maximum amount you desire to pay. Our default CPM of $2.00 is considered to be a healthy position to start with. Raise the bid on sites that are responsive to ensure you are winning a desirable amount of the inventory to test with, or to scale on. Ineffective sites can potentially become effective if you can obtain traffic for a lesser amount, so lowering your bid price before turning a site offline can help yield the desired result.<p> Contact your account manager for insights regarding how bid price and frequency caps affect impression depth.',

	'Why is my campaign not getting traffic?'=>'There are several reasons why your campaign may not be getting traffic:<br /> 		1. Account Balance (Is your account funded or depleted?)<br /> 		2. Daily or Lifetime Campaign Budget Reached<br /> 		3. Blocked Ad Attribute or Vertical<br /> 		4. No Creatives Online For Specific Ad Size<br /> 		5. Retargeting Audience Too Small<br /> 		6. Lack of Impressions Available for Geo Location<br /> 		7. Lack of Impressions Available for Banner Sizes<br /> 		8. Campaign is Running Outside Flight Dates<br /> ',

	'How do I get more traffic?'=>'There are several things you can do to get more traffic on our platform:<p> 1. Consider raising the bid to compete for more of the site’s available volume.<br /> 2. Raising your frequency cap will also ensure you win more impressions (showing ads more frequently to a user can result in higher CTR, or more visibility at the very least.)<br /> 3. Ensure you are using every ad size that the site has available.<br /> 4. Consider also adding more sites to your campaign.<br /> 5. Speak with your account manager about opening up new sites for you, or arranging Private Marketplace deals with publishers for more traffic.<br /> ',

	'Why is my budget never fully reached?'=>"There is a mechanism in place on the RTB platform that is used to prevent over-spending on the system. Due to the speed at which traffic can be bought on the system, this mechanism effectively throttles a campaign once it approaches the end of the budget (i.e., when there is $5.00 left.) So if you notice that your daily budget is never fully reached, it is not for lack of traffic, but because of this safety buffer.<p> For this reason, if your total daily budget is equal to, or less than, $5.00, your campaign will not get any traffic.",

	'What is Average CPM?'=>"Average CPM is the average winning price observed on our platform. Please note that this figure only reflects bid data on our platform, and that winning bid data from external platforms is not displayed.<p> In cases where the Average CPM is $0.00, it simply means that the system was unable to calculate an accurate average for that site, usually because no one has won traffic on it yet. ",

	'What is Default Bid vs. eCPM?'=>'The Default Bid column is the maximum CPM price that you are willing to pay for a given site.<p> The eCPM column reflects the actual CPM price that you are winning at, and paying.',

	'What are Impressions Bid vs. Impressions Won?'=>'The Impressions Bid column is displaying the amount of impressions that your specific campaign is bidding on, and that match your campaign targeting criteria. Impressions Bid is taking into consideration many factors, including the geo-region you are targeting, the banner sizes you added to your campaign, contextual targeting, audience targeting, device targeting, and every other filter you can apply to a campaign.<p> The Impressions Won column is displaying the amount of Impressions Bid that you have won. This is determined largely by your bid price and your frequency cap. Naturally, you only pay for Impressions Won.<p> The number of impressions you’ve won, over the number of impressions you’ve bid on, is known as your Win Rate (%).',

	'Frequency Cap: What is it? How does it work? What are best practices?'=>'Frequency cap defines how often you wish to display ads to the same user, within a given timeframe (usually every 24 hours.)<p> (Example: A frequency cap of 3 impressions per 12 hours means that each visitor will see your ads a maximum of 3 times within 12 hours.)<p> This process works via cookies, which are used to remember a visitor’s impression count. Our default setting of 3 times within 12 hours is a great starting point.<p> For campaigns with the goal of brand awareness, increasing this number is a good idea. For performance or direct response campaigns, keeping the frequency cap between 1 and 3 is typically ideal.<p> From a performance perspective, increasing or decreasing your frequency cap may impact your CTR and conversion rate (CR), which is why a balance must be found between banner burnout (oversaturation) and performance.',

	'Do I need to sign a contract with you?'=>'No, you do not need to sign any contract with us. Our service is Pay As You Go, and there is no month fees or any other hidden fee.',
	);